name: CI

on:
  push:
    branches: [ '**' ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # since the project is built in a container, and the container only mounts the directories
      # we want to cache, everything else will be discarded when the container is destroyed.
      # so we do not have to worry about Actions caching files we do not want cached
      - name: Cache .gradle/caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Run cibuild script
        id: cibuild
        run: ./scripts/cibuild

      - name: Generate changelog from commit history
        id: log
        run: echo '::set-output name=changelog::$(git log $(git describe --tags --abbrev=0)..HEAD --oneline)'

      - name: Upload the built artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.cibuild.outputs.jar }}
          path: build/libs/${{ steps.cibuild.outputs.jar }}

      - name: Create release if this is a tagged workflow
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: build/libs/${{ steps.cibuild.outputs.jar }}
          name: ForgeHax ${{ steps.cibuild.outputs.version }} for Minecraft ${{ steps.cibuild.outputs.mcversion }}
          body: ${{ steps.log.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
