name: CI

on:
  push:
    branches: [ '**' ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache .gradle/caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/forge_gradle
            ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/libs.versions.toml', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run cibuild script
        id: exec
        run: ./scripts/cibuild

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Upload the built artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.exec.outputs.jar }}
          path: build/libs/${{ steps.exec.outputs.jar }}
          if-no-files-found: error

      - name: Create release if this is a tagged workflow
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: build/libs/${{ steps.exec.outputs.jar }}
          name: ForgeHax ${{ steps.exec.outputs.version }} for Minecraft ${{ steps.exec.outputs.mcversion }}
          body: ${{ steps.exec.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
